//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ent
{
    using System;
    using System.Collections.Generic;
    
    public partial class IL_PATIO_RESTARAUNT
    {
        public int ID_IL_PATIO_RESTARAUNT { get; set; }
        public int WAITHER_ID { get; set; }
        public int VISITOR_ID { get; set; }
        public int ITALIAN_MENU_PATIO_ID { get; set; }
    
        public virtual ITALIAN_MENU_PATIO ITALIAN_MENU_PATIO { get; set; }
        public virtual VISITOR VISITOR { get; set; }
        public virtual WAITHER WAITHER { get; set; }
    }
}
