//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ent
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EL_PATIOEntities : DbContext
    {
        public EL_PATIOEntities()
            : base("name=EL_PATIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ITALIAN_MENU_PATIO> ITALIAN_MENU_PATIO { get; set; }
        public virtual DbSet<VISITOR> VISITOR { get; set; }
        public virtual DbSet<WAITHER> WAITHER { get; set; }
        public virtual DbSet<IL_PATIO_RESTARAUNT> IL_PATIO_RESTARAUNT { get; set; }
    }
}
